export enum EMedicalSpecialty{
    ALERGOLOGIA = 'ALERGOLOGIA',
    ANGIOLOGIA = 'ANGIOLOGIA',
    BUCO_MAXILO = 'BUCO_MAXILO',
    CARDIOLOGIA_CLÍNCA = 'CARDIOLOGIA_CLÍNCA',
    CARDIOLOGIA_INFANTIL = 'CARDIOLOGIA_INFANTIL',
    CIRURGIA_CABEÇA_E_PESCOÇO = 'CIRURGIA_CABEÇA_E_PESCOÇO',
    CIRURGIA_CARDÍACA = 'CIRURGIA_CARDÍACA',
    CIRURGIA_DE_TÓRAX = 'CIRURGIA_DE_TÓRAX',
}