export enum EMedicalSpecialty{
    ALERGOLOGIA,
    ANGIOLOGIA,
    BUCO_MAXILO,
    CARDIOLOGIA_CLÍNCA,
    CARDIOLOGIA_INFANTIL,
    CIRURGIA_CABEÇA_E_PESCOÇO,
    CIRURGIA_CARDÍACA,
    CIRURGIA_DE_TÓRAX,
}